services:
  backend:
    image: ghcr.io/benjino16/ai-tomator/backend:latest
    command: uvicorn ai_tomator.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/ai_tomator
      - REDIS_URL=redis://redis:6379/0

      #Minio Config
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=llm-files
      - MINIO_SECURE=false  # "true" if TLS is activated

      #JWT Authentication Config
      - AUTH_REQUIRED=true #Set to false to enable local mode (no account system)
      - SECURE_COOKIES=true #Set to false to allow JWT authentication over HTTP (not secure!)
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440 # Time in minutes until the client has to log in again


    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

    depends_on:
      - db
      - redis

  worker:
    image: ghcr.io/benjino16/ai-tomator/backend:latest
    command: celery -A ai_tomator.celery.worker worker --loglevel=info -E
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/ai_tomator
      - REDIS_URL=redis://redis:6379/0

      #Minio Config
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=llm-files
      - MINIO_SECURE=false  # "true" if TLS is activated
    depends_on:
      - db
      - redis

  scheduler:
    image: ghcr.io/benjino16/ai-tomator/backend:latest
    command: celery -A ai_tomator.celery.worker beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/ai_tomator
      - REDIS_URL=redis://redis:6379/0

      #Minio Config
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=llm-files
      - MINIO_SECURE=false  # "true" if TLS is activated
    depends_on:
      - db
      - redis

  frontend:
    image: ghcr.io/benjino16/ai-tomator/frontend:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=ai_tomator
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data



volumes:
  postgres_data:
  redis_data:
  minio_data:
