services:
  backend:
    build: .
    environment:
      - SECURE_COOKIES=false

  worker:
    build: .
    command: celery -A ai_tomator.celery.worker worker --loglevel=info -E --concurrency=2

  frontend:
    build: ./frontend